- name: deploy ghost
  hosts: iliya
  vars:
    local_path: './ghost'
    remote_path: '~/ghost'
  remote_user: root
  tasks:
  - name: init docker.py
    command: /root/.pyenv/shims/pip install docker-compose
  - name: Ensures {{ remote_path }} dir exists
    file: path={{ remote_path }} state=directory
  - name: copy ghost file
    copy: 
      src: "{{ local_path }}/docker-compose.yaml"
      dest: "{{ remote_path }}/docker-compose.yaml"
      owner: root
      group: root 
      mode: 0644
      backup: yes
  - name: Stop ghost server
    docker_service:
      recreate: always
      project_src: ghost
    register: output
