- name: deploy nginx
  hosts: iliya
  vars:
    local_path: './nginx'
    remote_path: '~/nginx'
  remote_user: root
  tasks:
  # - name: init docker.py
  #   pip: 
  #   name: docker-compose
  - name: copy files
    copy: 
      src: "{{ local_path }}/"
      dest: "{{ remote_path }}/"
      owner: root
      group: root 
      mode: 0644
      backup: yes
  - name: Stop nginx server
    docker_service:
      project_src: nginx
      state: absent
  - name: Start up nginx server
    docker_service:
      project_src: nginx
    register: output

